-- =============================================================
-- NEON / POSTGRESQL NOTES
-- 1) Use the Neon PostgreSQL connection string in your backend DATABASE_URL.
-- 2) For serverless/high-concurrency application traffic, prefer Neon's pooled
--    connection string when supported by your database client/ORM.
-- 3) Store secrets only in environment variables; never commit the URL/password.
-- 4) PostgreSQL email uniqueness is case-sensitive by default. Normalize emails
--    to lowercase in the application, or later add a LOWER(email) unique index.
-- 5) This baseline intentionally preserves the existing 56-table architecture
--    and module boundaries; it does not create new business tables.
-- =============================================================

-- =============================================================
-- AUST ROBOTICS CLUB - CENTRAL MODULAR DATABASE
-- Target: Neon PostgreSQL / PostgreSQL 15+
-- Converted from the AUSTRC MySQL 8.0 baseline.
-- Uses PostgreSQL IDENTITY, JSONB, TIMESTAMPTZ, CREATE INDEX, and update triggers.
-- Purpose: ERD generation + implementation baseline
-- Modules:
--   1) SHARED / CORE     -> core_* and infra_*
--   2) EVENT MANAGEMENT -> evt_*
--   3) ADMINISTRATION   -> adm_*
--
-- Architectural rule:
--   evt_* and adm_* may reference core_* / infra_*.
--   core_* / infra_* NEVER reference evt_* or adm_* with FKs.
--   evt_* and adm_* do not directly reference each other.
-- =============================================================

-- =============================================================
-- 1. SHARED FEATURES / CORE DATABASE CONTRACT
-- =============================================================

CREATE TABLE core_users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NULL,
    auth_provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    email_verified_at TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_core_users_email UNIQUE (email)
);

CREATE TABLE infra_files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploaded_by_user_id BIGINT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NULL,
    storage_provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    storage_key VARCHAR(500) NOT NULL,
    public_url VARCHAR(1000) NULL,
    mime_type VARCHAR(150) NULL,
    file_size_bytes BIGINT NULL,
    checksum_sha256 VARCHAR(64) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    metadata JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_infra_files_storage_key UNIQUE (storage_key)
);

CREATE INDEX idx_infra_files_uploader ON infra_files (uploaded_by_user_id);

CREATE TABLE core_user_profiles (
    user_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    phone VARCHAR(50) NULL,
    gender VARCHAR(30) NULL,
    date_of_birth DATE NULL,
    photo_file_id BIGINT NULL,
    address_text VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (photo_file_id) REFERENCES infra_files(file_id) ON DELETE SET NULL,
    CONSTRAINT uk_core_user_profiles_user UNIQUE (user_id)
);

CREATE TABLE core_members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    member_code VARCHAR(100) NOT NULL,
    member_name VARCHAR(200) NOT NULL,
    primary_email VARCHAR(255) NULL,
    joined_at DATE NULL,
    left_at DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_core_members_member_code UNIQUE (member_code),
    CONSTRAINT uk_core_members_user UNIQUE (user_id)
);

CREATE INDEX idx_core_members_status ON core_members (status);

CREATE TABLE core_roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key VARCHAR(100) NOT NULL,
    role_name VARCHAR(150) NOT NULL,
    module_scope VARCHAR(30) NOT NULL DEFAULT 'GLOBAL',
    description VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_core_roles_key UNIQUE (role_key)
);

CREATE TABLE core_permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key VARCHAR(150) NOT NULL,
    permission_name VARCHAR(200) NOT NULL,
    module_scope VARCHAR(30) NOT NULL DEFAULT 'GLOBAL',
    description VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_core_permissions_key UNIQUE (permission_key)
);

CREATE TABLE core_role_permissions (
    role_permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES core_roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES core_permissions(permission_id) ON DELETE CASCADE,
    CONSTRAINT uk_core_role_permissions UNIQUE (role_id, permission_id)
);

CREATE TABLE core_user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    scope_module VARCHAR(30) NULL,
    scope_entity_id BIGINT NULL,
    assigned_by_user_id BIGINT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES core_roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_core_user_roles_scope UNIQUE (user_id, role_id, scope_module, scope_entity_id)
);

CREATE INDEX idx_core_user_roles_user ON core_user_roles (user_id);
CREATE INDEX idx_core_user_roles_role ON core_user_roles (role_id);

CREATE TABLE infra_document_templates (
    document_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key VARCHAR(120) NOT NULL,
    template_name VARCHAR(200) NOT NULL,
    module_scope VARCHAR(30) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    template_file_id BIGINT NULL,
    template_html TEXT NULL,
    configuration JSONB NULL,
    version_no INT NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (template_file_id) REFERENCES infra_files(file_id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_infra_document_templates_key_version UNIQUE (template_key, version_no)
);

CREATE TABLE infra_generated_documents (
    generated_document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_template_id BIGINT NULL,
    file_id BIGINT NOT NULL,
    generated_by_user_id BIGINT NULL,
    source_module VARCHAR(30) NOT NULL,
    source_entity_type VARCHAR(100) NOT NULL,
    source_entity_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    metadata JSONB NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (document_template_id) REFERENCES infra_document_templates(document_template_id) ON DELETE SET NULL,
    FOREIGN KEY (file_id) REFERENCES infra_files(file_id) ON DELETE RESTRICT,
    FOREIGN KEY (generated_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_infra_generated_documents_source ON infra_generated_documents (source_module, source_entity_type, source_entity_id);

CREATE TABLE infra_email_templates (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key VARCHAR(120) NOT NULL,
    name VARCHAR(200) NOT NULL,
    module_scope VARCHAR(30) NOT NULL,
    subject_template VARCHAR(500) NOT NULL,
    body_html TEXT NULL,
    body_text TEXT NULL,
    variables_schema JSONB NULL,
    version_no INT NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_infra_email_templates_key_version UNIQUE (template_key, version_no)
);

CREATE TABLE infra_email_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NULL,
    recipient_user_id BIGINT NULL,
    to_email VARCHAR(255) NOT NULL,
    cc_json JSONB NULL,
    bcc_json JSONB NULL,
    subject VARCHAR(500) NOT NULL,
    body_html TEXT NULL,
    body_text TEXT NULL,
    source_module VARCHAR(30) NOT NULL,
    source_entity_type VARCHAR(100) NULL,
    source_entity_id BIGINT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    queued_at TIMESTAMPTZ NULL,
    sent_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (template_id) REFERENCES infra_email_templates(template_id) ON DELETE SET NULL,
    FOREIGN KEY (recipient_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_infra_email_messages_status ON infra_email_messages (status);
CREATE INDEX idx_infra_email_messages_recipient ON infra_email_messages (recipient_user_id);
CREATE INDEX idx_infra_email_messages_source ON infra_email_messages (source_module, source_entity_type, source_entity_id);

CREATE TABLE infra_email_delivery_attempts (
    delivery_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    provider VARCHAR(100) NULL,
    provider_message_id VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    error_message TEXT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES infra_email_messages(message_id) ON DELETE CASCADE,
    CONSTRAINT uk_infra_email_delivery_attempt UNIQUE (message_id, attempt_no)
);

CREATE TABLE infra_audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NULL,
    module_name VARCHAR(30) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NULL,
    action VARCHAR(100) NOT NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    ip_address VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_infra_audit_logs_entity ON infra_audit_logs (module_name, entity_type, entity_id);
CREATE INDEX idx_infra_audit_logs_actor ON infra_audit_logs (actor_user_id);

-- =============================================================
-- 2. EVENT MANAGEMENT MODULE (evt_*)
-- =============================================================

CREATE TABLE evt_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    event_type VARCHAR(100) NULL,
    venue VARCHAR(255) NULL,
    start_at TIMESTAMPTZ NULL,
    end_at TIMESTAMPTZ NULL,
    registration_open_at TIMESTAMPTZ NULL,
    registration_close_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    organizer_reference VARCHAR(255) NULL,
    configuration JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_evt_events_status ON evt_events (status);
CREATE INDEX idx_evt_events_schedule ON evt_events (start_at, end_at);

CREATE TABLE evt_event_segments (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    segment_code VARCHAR(100) NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    capacity INT NULL,
    start_at TIMESTAMPTZ NULL,
    end_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    rules JSONB NULL,
    result_configuration JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_event_segments_code UNIQUE (event_id, segment_code)
);

CREATE INDEX idx_evt_event_segments_event ON evt_event_segments (event_id);
CREATE INDEX idx_evt_event_segments_status ON evt_event_segments (status);

CREATE TABLE evt_participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    participant_identifier VARCHAR(100) NOT NULL,
    display_name_snapshot VARCHAR(200) NOT NULL,
    email_snapshot VARCHAR(255) NULL,
    phone_snapshot VARCHAR(50) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_participants_identifier UNIQUE (participant_identifier)
);

CREATE INDEX idx_evt_participants_user ON evt_participants (user_id);

CREATE TABLE evt_registrations (
    registration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    registration_number VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ NULL,
    rejected_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    cancelled_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (participant_id) REFERENCES evt_participants(participant_id) ON DELETE RESTRICT,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_registrations_number UNIQUE (registration_number),
    CONSTRAINT uk_evt_registrations_participant_event UNIQUE (participant_id, event_id)
);

CREATE INDEX idx_evt_registrations_event_status ON evt_registrations (event_id, status);
CREATE INDEX idx_evt_registrations_participant ON evt_registrations (participant_id);

CREATE TABLE evt_registration_segments (
    registration_segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    segment_id BIGINT NOT NULL,
    participation_status VARCHAR(30) NOT NULL DEFAULT 'REGISTERED',
    eligible_for_result BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (segment_id) REFERENCES evt_event_segments(segment_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_registration_segments UNIQUE (registration_id, segment_id)
);

CREATE INDEX idx_evt_registration_segments_segment ON evt_registration_segments (segment_id);

CREATE TABLE evt_registration_fields (
    field_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    field_key VARCHAR(120) NOT NULL,
    label VARCHAR(255) NOT NULL,
    field_type VARCHAR(50) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    validation_rule JSONB NULL,
    sort_order INT NOT NULL DEFAULT 0,
    visibility VARCHAR(30) NOT NULL DEFAULT 'VISIBLE',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_registration_fields_key UNIQUE (event_id, field_key)
);

CREATE INDEX idx_evt_registration_fields_event_sort ON evt_registration_fields (event_id, sort_order);

CREATE TABLE evt_registration_field_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    option_value VARCHAR(255) NOT NULL,
    option_label VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (field_id) REFERENCES evt_registration_fields(field_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_registration_field_options_value UNIQUE (field_id, option_value)
);

CREATE INDEX idx_evt_registration_field_options_sort ON evt_registration_field_options (field_id, sort_order);

CREATE TABLE evt_registration_answers (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    field_id BIGINT NOT NULL,
    value_text TEXT NULL,
    value_number DECIMAL(18,4) NULL,
    value_date DATE NULL,
    value_json JSONB NULL,
    file_id BIGINT NULL,
    field_key_snapshot VARCHAR(120) NOT NULL,
    field_label_snapshot VARCHAR(255) NOT NULL,
    field_type_snapshot VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (field_id) REFERENCES evt_registration_fields(field_id) ON DELETE RESTRICT,
    FOREIGN KEY (file_id) REFERENCES infra_files(file_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_registration_answers UNIQUE (registration_id, field_id)
);

CREATE INDEX idx_evt_registration_answers_field ON evt_registration_answers (field_id);

CREATE TABLE evt_qr_codes (
    qr_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_qr_codes_registration UNIQUE (registration_id),
    CONSTRAINT uk_evt_qr_codes_token UNIQUE (token),
    CONSTRAINT uk_evt_qr_codes_token_hash UNIQUE (token_hash)
);

CREATE TABLE evt_service_types (
    service_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    default_multi_use BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evt_service_types_name UNIQUE (name)
);

CREATE TABLE evt_event_services (
    event_service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    service_type_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    configuration JSONB NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    multi_use BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    FOREIGN KEY (service_type_id) REFERENCES evt_service_types(service_type_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_event_services_name UNIQUE (event_id, name)
);

CREATE INDEX idx_evt_event_services_type ON evt_event_services (service_type_id);

CREATE TABLE evt_service_usage (
    service_usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_service_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    qr_code_id BIGINT NOT NULL,
    operator_user_id BIGINT NULL,
    usage_sequence INT NOT NULL DEFAULT 1,
    used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'SUCCESS',
    result VARCHAR(100) NULL,
    notes VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_service_id) REFERENCES evt_event_services(event_service_id) ON DELETE RESTRICT,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (qr_code_id) REFERENCES evt_qr_codes(qr_code_id) ON DELETE RESTRICT,
    FOREIGN KEY (operator_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_service_usage_sequence UNIQUE (event_service_id, registration_id, usage_sequence)
);

CREATE INDEX idx_evt_service_usage_registration ON evt_service_usage (registration_id);
CREATE INDEX idx_evt_service_usage_used_at ON evt_service_usage (used_at);

CREATE TABLE evt_event_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    segment_id BIGINT NULL,
    name VARCHAR(200) NOT NULL,
    start_at TIMESTAMPTZ NULL,
    end_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    FOREIGN KEY (segment_id) REFERENCES evt_event_segments(segment_id) ON DELETE SET NULL
);

CREATE INDEX idx_evt_event_sessions_event ON evt_event_sessions (event_id);
CREATE INDEX idx_evt_event_sessions_segment ON evt_event_sessions (segment_id);

CREATE TABLE evt_event_staff (
    event_staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT,
    FOREIGN KEY (role_id) REFERENCES core_roles(role_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_event_staff UNIQUE (event_id, user_id, role_id)
);

CREATE INDEX idx_evt_event_staff_user ON evt_event_staff (user_id);

CREATE TABLE evt_attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    operator_user_id BIGINT NULL,
    checked_in_at TIMESTAMPTZ NULL,
    checked_out_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PRESENT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES evt_event_sessions(session_id) ON DELETE RESTRICT,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (operator_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_attendance_session_registration UNIQUE (session_id, registration_id)
);

CREATE INDEX idx_evt_attendance_registration ON evt_attendance (registration_id);

CREATE TABLE evt_results (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_segment_id BIGINT NOT NULL,
    score DECIMAL(18,4) NULL,
    marks DECIMAL(18,4) NULL,
    time_value DECIMAL(18,4) NULL,
    textual_result VARCHAR(500) NULL,
    position_rank INT NULL,
    result_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMPTZ NULL,
    finalized_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_segment_id) REFERENCES evt_registration_segments(registration_segment_id) ON DELETE RESTRICT,
    CONSTRAINT uk_evt_results_registration_segment UNIQUE (registration_segment_id)
);

CREATE INDEX idx_evt_results_status ON evt_results (result_status);
CREATE INDEX idx_evt_results_position ON evt_results (position_rank);

CREATE TABLE evt_result_revisions (
    result_revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    previous_result JSONB NULL,
    new_result JSONB NOT NULL,
    reason VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (result_id) REFERENCES evt_results(result_id) ON DELETE RESTRICT,
    FOREIGN KEY (changed_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_evt_result_revisions_result ON evt_result_revisions (result_id);

CREATE TABLE evt_notification_events (
    notification_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NULL,
    event_id BIGINT NOT NULL,
    message_id BIGINT NULL,
    notification_type VARCHAR(60) NOT NULL,
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reference VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (event_id) REFERENCES evt_events(event_id) ON DELETE RESTRICT,
    FOREIGN KEY (message_id) REFERENCES infra_email_messages(message_id) ON DELETE SET NULL
);

CREATE INDEX idx_evt_notification_events_registration ON evt_notification_events (registration_id);
CREATE INDEX idx_evt_notification_events_event_type ON evt_notification_events (event_id, notification_type);

CREATE TABLE evt_certificate_eligibility (
    eligibility_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    registration_segment_id BIGINT NULL,
    eligibility_type VARCHAR(50) NOT NULL,
    eligible BOOLEAN NOT NULL DEFAULT FALSE,
    reason VARCHAR(500) NULL,
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    evaluated_by_user_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registration_id) REFERENCES evt_registrations(registration_id) ON DELETE RESTRICT,
    FOREIGN KEY (registration_segment_id) REFERENCES evt_registration_segments(registration_segment_id) ON DELETE RESTRICT,
    FOREIGN KEY (evaluated_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_certificate_eligibility UNIQUE (registration_id, registration_segment_id, eligibility_type)
);

CREATE INDEX idx_evt_certificate_eligibility_registration ON evt_certificate_eligibility (registration_id);

CREATE TABLE evt_certificates (
    certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eligibility_id BIGINT NOT NULL,
    certificate_number VARCHAR(120) NOT NULL,
    document_template_id BIGINT NULL,
    generated_document_id BIGINT NULL,
    recipient_name_snapshot VARCHAR(200) NOT NULL,
    event_name_snapshot VARCHAR(255) NOT NULL,
    segment_name_snapshot VARCHAR(255) NULL,
    position_snapshot VARCHAR(100) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    issued_at TIMESTAMPTZ NULL,
    available_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (eligibility_id) REFERENCES evt_certificate_eligibility(eligibility_id) ON DELETE RESTRICT,
    FOREIGN KEY (document_template_id) REFERENCES infra_document_templates(document_template_id) ON DELETE SET NULL,
    FOREIGN KEY (generated_document_id) REFERENCES infra_generated_documents(generated_document_id) ON DELETE SET NULL,
    CONSTRAINT uk_evt_certificates_eligibility UNIQUE (eligibility_id),
    CONSTRAINT uk_evt_certificates_number UNIQUE (certificate_number),
    CONSTRAINT uk_evt_certificates_generated_document UNIQUE (generated_document_id)
);

-- =============================================================
-- 3. ADMINISTRATION MODULE (adm_*)
-- =============================================================

CREATE TABLE adm_forms (
    form_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_key VARCHAR(120) NOT NULL,
    form_name VARCHAR(255) NOT NULL,
    form_description TEXT NULL,
    form_type VARCHAR(80) NOT NULL,
    opening_time TIMESTAMPTZ NULL,
    closing_time TIMESTAMPTZ NULL,
    owner_user_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    settings JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_forms_key UNIQUE (form_key)
);

CREATE INDEX idx_adm_forms_status ON adm_forms (status);
CREATE INDEX idx_adm_forms_type ON adm_forms (form_type);

CREATE TABLE adm_form_fields (
    field_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT NOT NULL,
    field_key VARCHAR(120) NOT NULL,
    label VARCHAR(255) NOT NULL,
    field_type VARCHAR(50) NOT NULL,
    validation_rule JSONB NULL,
    sort_order INT NOT NULL DEFAULT 0,
    visibility VARCHAR(30) NOT NULL DEFAULT 'VISIBLE',
    required_flag BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (form_id) REFERENCES adm_forms(form_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_form_fields_key UNIQUE (form_id, field_key)
);

CREATE INDEX idx_adm_form_fields_sort ON adm_form_fields (form_id, sort_order);

CREATE TABLE adm_form_field_options (
    field_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    option_value VARCHAR(255) NOT NULL,
    option_label VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (field_id) REFERENCES adm_form_fields(field_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_form_field_options_value UNIQUE (field_id, option_value)
);

CREATE INDEX idx_adm_form_field_options_sort ON adm_form_field_options (field_id, sort_order);

CREATE TABLE adm_form_submissions (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT NOT NULL,
    applicant_user_id BIGINT NULL,
    submission_number VARCHAR(120) NOT NULL,
    applicant_name_snapshot VARCHAR(200) NULL,
    applicant_email_snapshot VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ NULL,
    withdrawn_at TIMESTAMPTZ NULL,
    reviewed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (form_id) REFERENCES adm_forms(form_id) ON DELETE RESTRICT,
    FOREIGN KEY (applicant_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_adm_form_submissions_number UNIQUE (submission_number)
);

CREATE INDEX idx_adm_form_submissions_form_status ON adm_form_submissions (form_id, status);
CREATE INDEX idx_adm_form_submissions_applicant ON adm_form_submissions (applicant_user_id);

CREATE TABLE adm_form_answers (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    field_id BIGINT NOT NULL,
    value_text TEXT NULL,
    value_number DECIMAL(18,4) NULL,
    value_date DATE NULL,
    value_json JSONB NULL,
    file_id BIGINT NULL,
    field_key_snapshot VARCHAR(120) NOT NULL,
    field_label_snapshot VARCHAR(255) NOT NULL,
    field_type_snapshot VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (submission_id) REFERENCES adm_form_submissions(submission_id) ON DELETE RESTRICT,
    FOREIGN KEY (field_id) REFERENCES adm_form_fields(field_id) ON DELETE RESTRICT,
    FOREIGN KEY (file_id) REFERENCES infra_files(file_id) ON DELETE SET NULL,
    CONSTRAINT uk_adm_form_answers UNIQUE (submission_id, field_id)
);

CREATE INDEX idx_adm_form_answers_field ON adm_form_answers (field_id);

CREATE TABLE adm_form_answer_options (
    answer_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id BIGINT NOT NULL,
    field_option_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (answer_id) REFERENCES adm_form_answers(answer_id) ON DELETE CASCADE,
    FOREIGN KEY (field_option_id) REFERENCES adm_form_field_options(field_option_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_form_answer_options UNIQUE (answer_id, field_option_id)
);

CREATE TABLE adm_application_reviews (
    application_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    reviewer_user_id BIGINT NOT NULL,
    selection_status VARCHAR(30) NOT NULL,
    remarks TEXT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (submission_id) REFERENCES adm_form_submissions(submission_id) ON DELETE RESTRICT,
    FOREIGN KEY (reviewer_user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT
);

CREATE INDEX idx_adm_application_reviews_submission ON adm_application_reviews (submission_id);
CREATE INDEX idx_adm_application_reviews_reviewer ON adm_application_reviews (reviewer_user_id);

CREATE TABLE adm_application_status_history (
    application_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    changed_by_user_id BIGINT NULL,
    reason VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (submission_id) REFERENCES adm_form_submissions(submission_id) ON DELETE RESTRICT,
    FOREIGN KEY (changed_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_adm_application_status_history_submission ON adm_application_status_history (submission_id);

CREATE TABLE adm_panel_terms (
    panel_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_title VARCHAR(200) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_adm_panel_terms_title UNIQUE (panel_title)
);

CREATE TABLE adm_positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_key VARCHAR(100) NOT NULL,
    position_name VARCHAR(150) NOT NULL,
    hierarchy_level INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    can_assign_tasks BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_adm_positions_key UNIQUE (position_key),
    CONSTRAINT uk_adm_positions_name UNIQUE (position_name)
);

CREATE TABLE adm_teams (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_key VARCHAR(100) NOT NULL,
    team_name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_adm_teams_key UNIQUE (team_key),
    CONSTRAINT uk_adm_teams_name UNIQUE (team_name)
);

CREATE TABLE adm_panel_memberships (
    panel_membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_term_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    team_id BIGINT NULL,
    appointed_at DATE NOT NULL,
    ended_at DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    notes VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (panel_term_id) REFERENCES adm_panel_terms(panel_term_id) ON DELETE RESTRICT,
    FOREIGN KEY (member_id) REFERENCES core_members(member_id) ON DELETE RESTRICT,
    FOREIGN KEY (position_id) REFERENCES adm_positions(position_id) ON DELETE RESTRICT,
    FOREIGN KEY (team_id) REFERENCES adm_teams(team_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_panel_memberships_history UNIQUE (panel_term_id, member_id, position_id, team_id, appointed_at)
);

CREATE INDEX idx_adm_panel_memberships_member ON adm_panel_memberships (member_id);
CREATE INDEX idx_adm_panel_memberships_term_team ON adm_panel_memberships (panel_term_id, team_id);
CREATE INDEX idx_adm_panel_memberships_position ON adm_panel_memberships (position_id);

CREATE TABLE adm_member_certificates (
    member_certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_membership_id BIGINT NOT NULL,
    certificate_number VARCHAR(120) NOT NULL,
    document_template_id BIGINT NULL,
    generated_document_id BIGINT NULL,
    snapshot_date DATE NOT NULL,
    member_name_snapshot VARCHAR(200) NOT NULL,
    term_snapshot VARCHAR(200) NOT NULL,
    position_snapshot VARCHAR(150) NOT NULL,
    team_snapshot VARCHAR(150) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    issued_at TIMESTAMPTZ NULL,
    available_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (panel_membership_id) REFERENCES adm_panel_memberships(panel_membership_id) ON DELETE RESTRICT,
    FOREIGN KEY (document_template_id) REFERENCES infra_document_templates(document_template_id) ON DELETE SET NULL,
    FOREIGN KEY (generated_document_id) REFERENCES infra_generated_documents(generated_document_id) ON DELETE SET NULL,
    CONSTRAINT uk_adm_member_certificates_membership UNIQUE (panel_membership_id),
    CONSTRAINT uk_adm_member_certificates_number UNIQUE (certificate_number),
    CONSTRAINT uk_adm_member_certificates_document UNIQUE (generated_document_id)
);

CREATE TABLE adm_email_campaigns (
    email_campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_name VARCHAR(255) NOT NULL,
    campaign_type VARCHAR(80) NOT NULL,
    form_id BIGINT NULL,
    template_id BIGINT NULL,
    created_by_user_id BIGINT NOT NULL,
    target_definition JSONB NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    scheduled_at TIMESTAMPTZ NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (form_id) REFERENCES adm_forms(form_id) ON DELETE SET NULL,
    FOREIGN KEY (template_id) REFERENCES infra_email_templates(template_id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT
);

CREATE INDEX idx_adm_email_campaigns_status ON adm_email_campaigns (status);
CREATE INDEX idx_adm_email_campaigns_form ON adm_email_campaigns (form_id);

CREATE TABLE adm_email_campaign_recipients (
    campaign_recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_campaign_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    member_id BIGINT NULL,
    submission_id BIGINT NULL,
    message_id BIGINT NULL,
    recipient_name VARCHAR(200) NULL,
    recipient_email VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (email_campaign_id) REFERENCES adm_email_campaigns(email_campaign_id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (member_id) REFERENCES core_members(member_id) ON DELETE SET NULL,
    FOREIGN KEY (submission_id) REFERENCES adm_form_submissions(submission_id) ON DELETE SET NULL,
    FOREIGN KEY (message_id) REFERENCES infra_email_messages(message_id) ON DELETE SET NULL,
    CONSTRAINT uk_adm_campaign_recipient_email UNIQUE (email_campaign_id, recipient_email)
);

CREATE INDEX idx_adm_campaign_recipients_status ON adm_email_campaign_recipients (email_campaign_id, status);

CREATE TABLE adm_tasks (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_term_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    assigner_membership_id BIGINT NOT NULL,
    task_title VARCHAR(255) NOT NULL,
    task_description TEXT NULL,
    priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(30) NOT NULL DEFAULT 'TODO',
    due_at TIMESTAMPTZ NULL,
    blocked_reason VARCHAR(500) NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (panel_term_id) REFERENCES adm_panel_terms(panel_term_id) ON DELETE RESTRICT,
    FOREIGN KEY (team_id) REFERENCES adm_teams(team_id) ON DELETE RESTRICT,
    FOREIGN KEY (assigner_membership_id) REFERENCES adm_panel_memberships(panel_membership_id) ON DELETE RESTRICT
);

CREATE INDEX idx_adm_tasks_team_status ON adm_tasks (team_id, status);
CREATE INDEX idx_adm_tasks_due_at ON adm_tasks (due_at);
CREATE INDEX idx_adm_tasks_assigner ON adm_tasks (assigner_membership_id);

CREATE TABLE adm_task_assignees (
    task_assignee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    panel_membership_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'ASSIGNED',
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES adm_tasks(task_id) ON DELETE RESTRICT,
    FOREIGN KEY (panel_membership_id) REFERENCES adm_panel_memberships(panel_membership_id) ON DELETE RESTRICT,
    FOREIGN KEY (assigned_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_adm_task_assignees UNIQUE (task_id, panel_membership_id)
);

CREATE INDEX idx_adm_task_assignees_membership ON adm_task_assignees (panel_membership_id);

CREATE TABLE adm_task_status_history (
    task_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    changed_by_user_id BIGINT NULL,
    reason VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES adm_tasks(task_id) ON DELETE RESTRICT,
    FOREIGN KEY (changed_by_user_id) REFERENCES core_users(user_id) ON DELETE SET NULL
);

CREATE INDEX idx_adm_task_status_history_task ON adm_task_status_history (task_id);

CREATE TABLE adm_task_submissions (
    task_submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_assignee_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    submission_text TEXT NULL,
    submission_link VARCHAR(1000) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_assignee_id) REFERENCES adm_task_assignees(task_assignee_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_task_submissions_version UNIQUE (task_assignee_id, version_no)
);

CREATE INDEX idx_adm_task_submissions_status ON adm_task_submissions (status);

CREATE TABLE adm_task_submission_files (
    task_submission_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_submission_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_submission_id) REFERENCES adm_task_submissions(task_submission_id) ON DELETE RESTRICT,
    FOREIGN KEY (file_id) REFERENCES infra_files(file_id) ON DELETE RESTRICT,
    CONSTRAINT uk_adm_task_submission_files UNIQUE (task_submission_id, file_id)
);

CREATE TABLE adm_task_submission_reviews (
    task_submission_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_submission_id BIGINT NOT NULL,
    reviewer_user_id BIGINT NOT NULL,
    review_status VARCHAR(30) NOT NULL,
    remarks TEXT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_submission_id) REFERENCES adm_task_submissions(task_submission_id) ON DELETE RESTRICT,
    FOREIGN KEY (reviewer_user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT
);

CREATE INDEX idx_adm_task_submission_reviews_submission ON adm_task_submission_reviews (task_submission_id);

CREATE TABLE adm_task_comments (
    task_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    parent_comment_id BIGINT NULL,
    comment_type VARCHAR(30) NOT NULL DEFAULT 'COMMENT',
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES adm_tasks(task_id) ON DELETE RESTRICT,
    FOREIGN KEY (author_user_id) REFERENCES core_users(user_id) ON DELETE RESTRICT,
    FOREIGN KEY (parent_comment_id) REFERENCES adm_task_comments(task_comment_id) ON DELETE SET NULL
);

CREATE INDEX idx_adm_task_comments_task ON adm_task_comments (task_id);
CREATE INDEX idx_adm_task_comments_author ON adm_task_comments (author_user_id);


-- =============================================================
-- POSTGRESQL AUTOMATIC updated_at SUPPORT
-- MySQL's "ON UPDATE CURRENT_TIMESTAMP" does not exist in PostgreSQL.
-- This reusable trigger preserves the same behavior.
-- =============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_core_users_set_updated_at
BEFORE UPDATE ON core_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_infra_files_set_updated_at
BEFORE UPDATE ON infra_files
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_core_user_profiles_set_updated_at
BEFORE UPDATE ON core_user_profiles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_core_members_set_updated_at
BEFORE UPDATE ON core_members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_core_roles_set_updated_at
BEFORE UPDATE ON core_roles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_core_permissions_set_updated_at
BEFORE UPDATE ON core_permissions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_infra_document_templates_set_updated_at
BEFORE UPDATE ON infra_document_templates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_infra_email_templates_set_updated_at
BEFORE UPDATE ON infra_email_templates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_infra_email_messages_set_updated_at
BEFORE UPDATE ON infra_email_messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_events_set_updated_at
BEFORE UPDATE ON evt_events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_event_segments_set_updated_at
BEFORE UPDATE ON evt_event_segments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_participants_set_updated_at
BEFORE UPDATE ON evt_participants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_registrations_set_updated_at
BEFORE UPDATE ON evt_registrations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_registration_segments_set_updated_at
BEFORE UPDATE ON evt_registration_segments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_registration_fields_set_updated_at
BEFORE UPDATE ON evt_registration_fields
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_registration_field_options_set_updated_at
BEFORE UPDATE ON evt_registration_field_options
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_registration_answers_set_updated_at
BEFORE UPDATE ON evt_registration_answers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_qr_codes_set_updated_at
BEFORE UPDATE ON evt_qr_codes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_service_types_set_updated_at
BEFORE UPDATE ON evt_service_types
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_event_services_set_updated_at
BEFORE UPDATE ON evt_event_services
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_event_sessions_set_updated_at
BEFORE UPDATE ON evt_event_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_event_staff_set_updated_at
BEFORE UPDATE ON evt_event_staff
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_attendance_set_updated_at
BEFORE UPDATE ON evt_attendance
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_results_set_updated_at
BEFORE UPDATE ON evt_results
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_notification_events_set_updated_at
BEFORE UPDATE ON evt_notification_events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_certificate_eligibility_set_updated_at
BEFORE UPDATE ON evt_certificate_eligibility
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_evt_certificates_set_updated_at
BEFORE UPDATE ON evt_certificates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_forms_set_updated_at
BEFORE UPDATE ON adm_forms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_form_fields_set_updated_at
BEFORE UPDATE ON adm_form_fields
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_form_field_options_set_updated_at
BEFORE UPDATE ON adm_form_field_options
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_form_submissions_set_updated_at
BEFORE UPDATE ON adm_form_submissions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_form_answers_set_updated_at
BEFORE UPDATE ON adm_form_answers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_panel_terms_set_updated_at
BEFORE UPDATE ON adm_panel_terms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_positions_set_updated_at
BEFORE UPDATE ON adm_positions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_teams_set_updated_at
BEFORE UPDATE ON adm_teams
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_panel_memberships_set_updated_at
BEFORE UPDATE ON adm_panel_memberships
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_member_certificates_set_updated_at
BEFORE UPDATE ON adm_member_certificates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_email_campaigns_set_updated_at
BEFORE UPDATE ON adm_email_campaigns
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_email_campaign_recipients_set_updated_at
BEFORE UPDATE ON adm_email_campaign_recipients
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_tasks_set_updated_at
BEFORE UPDATE ON adm_tasks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_task_assignees_set_updated_at
BEFORE UPDATE ON adm_task_assignees
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_task_submissions_set_updated_at
BEFORE UPDATE ON adm_task_submissions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_adm_task_comments_set_updated_at
BEFORE UPDATE ON adm_task_comments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =============================================================
-- END OF AUSTRC CENTRAL MODULAR DATABASE
-- =============================================================
